controllers/base_controller.py
from flask import render_template, request, redirect
from flask import Blueprint
import repositories.translated_phrase_repository as translated_phrase_repository
import repositories.tag_repository as tag_repository
import repositories.tag_translated_phrase_repository as tag_translated_phrase_repository
from models.tag import Tag
import random

base_blueprint = Blueprint("base", __name__)


@base_blueprint.route('/')
def index():
    return render_template('index.html', title='Home')

@base_blueprint.route('/info')
def info():
    return render_template('info.html', title="Info")

@base_blueprint.route('/create_new_tag')
def create_new_tag():
    all_tags = tag_repository.select_all()
    return render_template('create_new_tag.html', title="Create A New Tag", all_tags=all_tags)

# to go to the page to create a new tag
# call the function create_new_tag()
# inside the function select all the tags currently in the databse using tag_repository.select_all()
# and save this list to a variable name all_tags
# the function must return render_template with the parameters of the html page for create_new_tag, the title "Create a New Tag", and the list of tags all_tags

@base_blueprint.route('/create_new_tag/new', methods=["POST"])
def save_created_tag():
    title = request.form['new_tag']
    tag = Tag(title.replace(" ", "-"))
    tag_repository.save(tag)
    return redirect('/create_new_tag')

@base_blueprint.route('/create_new_tag/<id>/delete', methods=["POST"])
def delete_tag(id):
    tag_translated_phrase_repository.delete_by_tag_id(id)
    tag_repository.delete(id)
    return redirect('/create_new_tag')
    
@base_blueprint.route('/random')
def play_random():
    all_ids = translated_phrase_repository.list_all_ids()
    number = len(all_ids) -1
    random_number = random.randint(0, number)
    random_id = all_ids[random_number]
    # all_translated_phrases = translated_phrase_repository.select_all()
    # number = len(all_translated_phrases)
    # random_number = random.randint(1, number)
    return redirect(f"/sentence_snaps/{random_id}/play")

controllers/languages_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.language import Language
import repositories.language_repository as language_repository
import repositories.translated_phrase_repository as translated_phrase_repository
import repositories.tag_translated_phrase_repository as tag_translated_phrase_repository

language_blueprint = Blueprint("language_blueprint", __name__)

@language_blueprint.route('/add_new_language')
def add_new_language():
    all_languages = language_repository.select_all()
    return render_template('new_languages/new_language.html', all_languages=all_languages)

@language_blueprint.route('/add_new_language/new', methods=['POST'])
def create_new_language():
    title = request.form['new_language']
    language = Language(title)
    language_repository.save(language)
    return redirect('/add_new_language')

@language_blueprint.route('/add_new_language/<id>/delete', methods=["POST"])
def delete_language(id):
    translated_phrases = translated_phrase_repository.select_by_language(id)
    for translated_phrase in translated_phrases:
        tag_translated_phrase_repository.delete_by_translated_phrase(translated_phrase)
    translated_phrase_repository.delete_by_language(id)
    language_repository.delete(id)
    return redirect('/add_new_language')

controllers/mastered_snaps_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.translated_phrase import TranslatedPhrase
from models.first_language_phrase import FirstLanguagePhrase
from models.language import Language
from models.tag import Tag
from models.tag_translated_phrase import tagTranslatedPhrase
import repositories.translated_phrase_repository as translated_phrase_repository
import repositories.first_language_phrase_repository as first_language_phrase_repository
import repositories.language_repository as language_repository
import repositories.tag_repository as tag_repository
import repositories.tag_translated_phrase_repository as tag_translated_phrase_repository
import string

mastered_snaps_blueprint = Blueprint("mastered_snaps_blueprint", __name__)

@mastered_snaps_blueprint.route("/mastered_snaps")
def mastered_snaps():
    mastered_translated_phrases = translated_phrase_repository.select_all_mastered()
    tag_translated_phrases = tag_translated_phrase_repository.select_all()
    return render_template("mastered_snaps/index.html",  mastered_translated_phrases=mastered_translated_phrases, tag_translated_phrases=tag_translated_phrases)

@mastered_snaps_blueprint.route("/mastered_snaps/<id>/delete", methods=["POST"])
def delete_phrase(id):
    translated_phrase_repository.delete(id)
    return redirect("/mastered_snaps")

@mastered_snaps_blueprint.route("/mastered_snaps/<id>/play")
def play_phrase(id):
    translated_phrase = translated_phrase_repository.select(id)
    return render_template("mastered_snaps/play.html", translated_phrase=translated_phrase)

@mastered_snaps_blueprint.route("/mastered_snaps/<id>/edit")
def edit_phrase(id):
    tag_translated_phrases = tag_translated_phrase_repository.select_all()
    all_tags = tag_repository.select_all()
    languages = language_repository.select_all()
    translated_phrase = translated_phrase_repository.select(id)
    tag_titles= translated_phrase_repository.tag_titles(translated_phrase)
    first_language_phrase = first_language_phrase_repository.select(translated_phrase.first_language_phrase.id)
    return render_template("mastered_snaps/edit.html", languages=languages, translated_phrase=translated_phrase, first_language_phrase=first_language_phrase, all_tags=all_tags, tag_translated_phrases=tag_translated_phrases, tag_titles=tag_titles)

@mastered_snaps_blueprint.route("/mastered_snaps/<id>", methods=['POST'])
def update_phrase(id):
    translated_phrase = translated_phrase_repository.select(id)
    original_first_language_phrase_id = translated_phrase.first_language_phrase.id
    language = language_repository.select_title(request.form['language_choice'])
    first_language_input = request.form['first_language_input']
    difficulty = request.form['difficulty_choice']
    translated_input = request.form['translated_input']
    mastered = False if "mastered" in request.form else True
    new_first_language_phrase = FirstLanguagePhrase(first_language_input, difficulty, original_first_language_phrase_id)
    first_language_phrase_repository.update(new_first_language_phrase)
    #first language phrase updated
    new_translated_phrase = TranslatedPhrase(translated_input, language, new_first_language_phrase, mastered, id)
    translated_phrase_repository.update(new_translated_phrase)
    #translated phrase updated
    #REMOVE TAGS
    if request.form['remove_tags'] != 'none':
        tag_to_remove = tag_repository.select_title(request.form['remove_tags'])
        tag_translated_phrase_repository.delete_row(new_translated_phrase, tag_to_remove)
    #ADD TAGS
    if request.form['tags'] != 'none':
        new_tag = tag_repository.select_title(request.form['tags'])
        tag_translated_phrase = tagTranslatedPhrase(new_translated_phrase, new_tag)
        tag_translated_phrase_repository.save(tag_translated_phrase)
    return redirect('/mastered_snaps')

@mastered_snaps_blueprint.route("/mastered_snaps/<id>/results", methods=["POST"])
def results(id):
    translated_phrase = translated_phrase_repository.select(id)
    answer = request.form['answer']
    remove_punctuation_answer = answer.translate(str.maketrans('','', string.punctuation))
    clean_answer = remove_punctuation_answer.lower()
    remove_punctuation_translated_phrase = translated_phrase.phrase.translate(str.maketrans('','',string.punctuation))
    clean_translated_phrase = remove_punctuation_translated_phrase.lower()
    id = id
    if clean_answer == clean_translated_phrase:
        result = True
    else:
        result = False
    return render_template("mastered_snaps/results.html", result=result, translated_phrase=translated_phrase, answer=answer, id=id)

@mastered_snaps_blueprint.route("/mastered_snaps/<id>/update_mastered", methods=["POST"])
def update_mastered(id):
    translated_phrase = translated_phrase_repository.select(id)
    phrase = translated_phrase.phrase
    language = translated_phrase.language
    first_language_phrase = translated_phrase.first_language_phrase
    mastered = False
    new_translated_phrase = TranslatedPhrase(phrase, language, first_language_phrase, mastered, id)
    translated_phrase_repository.update(new_translated_phrase)
    return redirect('/mastered_snaps')

@mastered_snaps_blueprint.route("/mastered_snaps/<id>/show_answer")
def show_answer(id):
    translated_phrase = translated_phrase_repository.select(id)
    return render_template("mastered_snaps/show_answer.html", translated_phrase=translated_phrase)

controllers/sentence_snaps_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.tag_translated_phrase import tagTranslatedPhrase
from models.first_language_phrase import FirstLanguagePhrase
from models.translated_phrase import TranslatedPhrase
from models.language import Language
import repositories.first_language_phrase_repository as first_language_phrase_repository
import repositories.translated_phrase_repository as translated_phrase_repository
import repositories.language_repository as language_repository
import repositories.tag_repository as tag_repository
import repositories.tag_translated_phrase_repository as tag_translated_phrase_repository

import string

sentence_snaps_blueprint = Blueprint("sentence_snaps_blueprint", __name__ )

@sentence_snaps_blueprint.route("/")
# @sentence_snaps_blueprint.route("/sentence_snaps")
def sentence_snaps():
    all_languages =language_repository.select_all()
    all_tags = tag_repository.select_all()
    unmastered_translated_phrases = translated_phrase_repository.select_all_unmastered()
    tag_translated_phrases = tag_translated_phrase_repository.select_all()
    return render_template("index.html", unmastered_translated_phrases=unmastered_translated_phrases, tag_translated_phrases=tag_translated_phrases, all_tags=all_tags, all_languages=all_languages)
    # return render_template("sentence_snaps/index.html", unmastered_translated_phrases=unmastered_translated_phrases, tag_translated_phrases=tag_translated_phrases, all_tags=all_tags, all_languages=all_languages)

@sentence_snaps_blueprint.route("/sentence_snaps/<id>/delete", methods=["POST"])
def delete_phrase(id):
    translated_phrase_repository.delete(id)
    return redirect("/")
    

@sentence_snaps_blueprint.route("/sentence_snaps/<id>/play")
def play_phrase(id):
    translated_phrase = translated_phrase_repository.select(id)
    return render_template("sentence_snaps/play.html", translated_phrase=translated_phrase)

@sentence_snaps_blueprint.route("/sentence_snaps/<id>/edit")
def edit_phrase(id):
    tag_translated_phrases = tag_translated_phrase_repository.select_all()
    all_tags = tag_repository.select_all()
    languages = language_repository.select_all()
    translated_phrase = translated_phrase_repository.select(id)
    tag_titles = translated_phrase_repository.tag_titles(translated_phrase)
    first_language_phrase = first_language_phrase_repository.select(translated_phrase.first_language_phrase.id)
    return render_template("sentence_snaps/edit.html", first_language_phrase=first_language_phrase, translated_phrase=translated_phrase, languages=languages, all_tags=all_tags, tag_translated_phrases=tag_translated_phrases, tag_titles=tag_titles)

@sentence_snaps_blueprint.route("/sentence_snaps/<id>", methods=['POST'])
def update_phrase(id):
    translated_phrase = translated_phrase_repository.select(id)
    original_first_language_phrase_id = translated_phrase.first_language_phrase.id
    language = language_repository.select_title(request.form['language_choice'])
    first_language_input = request.form['first_language_input']
    difficulty = request.form['difficulty_choice']
    translated_input = request.form['translated_input']
    mastered = True if "mastered" in request.form else False
    new_first_language_phrase = FirstLanguagePhrase(first_language_input, difficulty, original_first_language_phrase_id)
    first_language_phrase_repository.update(new_first_language_phrase)
    # first language phrase is updated now
    new_translated_phrase = TranslatedPhrase(translated_input, language, new_first_language_phrase, mastered, id)
    translated_phrase_repository.update(new_translated_phrase)
    # translated phrase is updated
    #REMOVE TAGS
    if request.form['remove_tags'] != 'none':
        tag_to_remove = tag_repository.select_title(request.form['remove_tags'])
        tag_translated_phrase_repository.delete_row(new_translated_phrase, tag_to_remove)
        print("Hello blablabal")
    #ADD TAGS
    if request.form['tags'] != 'none':
        new_tag = tag_repository.select_title(request.form['tags'])
        tag_translated_phrase = tagTranslatedPhrase(new_translated_phrase, new_tag)
        tag_translated_phrase_repository.save(tag_translated_phrase)
    return redirect('/')
    

@sentence_snaps_blueprint.route("/sentence_snaps/new")
def new_phrase():
    languages = language_repository.select_all()
    return render_template("sentence_snaps/new.html", languages=languages)

@sentence_snaps_blueprint.route("/", methods=["POST"])
def create_phrase():
    mastered = False
    language_input = request.form['language_choice']
    first_language_input = request.form['first_language_input']
    difficulty = request.form['difficulty_choice']
    translated_input = request.form['translated_input'].strip()
    language = language_repository.select_title(language_input)
    first_language_phrase = FirstLanguagePhrase(first_language_input, difficulty)
    first_language_phrase_repository.save(first_language_phrase)
    translated_phrase = TranslatedPhrase(translated_input, language, first_language_phrase, mastered)
    translated_phrase_repository.save(translated_phrase)
    return redirect('/')

@sentence_snaps_blueprint.route("/sentence_snaps/<id>/results", methods=["POST"])
def results(id):
    translated_phrase = translated_phrase_repository.select(id)
    answer = request.form['answer'].strip()
    remove_punctuation_answer = answer.translate(str.maketrans('','', string.punctuation))
    clean_answer = remove_punctuation_answer.lower()
    remove_punctuation_translated_phrase = translated_phrase.phrase.translate(str.maketrans('','',string.punctuation))
    clean_translated_phrase = remove_punctuation_translated_phrase.lower()
    id = id
    if clean_answer == clean_translated_phrase:
        result = True
    else:
        result = False
    return render_template("sentence_snaps/results.html", result=result, translated_phrase=translated_phrase, answer=answer, id=id)

@sentence_snaps_blueprint.route("/sentence_snaps/<id>/update_mastered", methods=["POST"])
def update_mastered(id):
    translated_phrase = translated_phrase_repository.select(id)
    phrase = translated_phrase.phrase
    language = translated_phrase.language
    first_language_phrase = translated_phrase.first_language_phrase
    mastered = True
    new_translated_phrase = TranslatedPhrase(phrase, language, first_language_phrase, mastered, id)
    translated_phrase_repository.update(new_translated_phrase)
    return redirect('/')

@sentence_snaps_blueprint.route("/sentence_snaps/<id>/show_answer")
def show_answer(id):
    translated_phrase = translated_phrase_repository.select(id)
    return render_template("/sentence_snaps/show_answer.html", translated_phrase=translated_phrase)

@sentence_snaps_blueprint.route("/sentence_snaps/filter", methods=["POST"])
def filter_snaps():
    if request.form['tag_choice'] == 'show_all':
        return redirect('/')
    tags_translated_phrases = tag_translated_phrase_repository.select_all()
    all_languages = language_repository.select_all()
    all_tags = tag_repository.select_all()
    chosen_tag = tag_repository.select_title(request.form['tag_choice'])
    all_translated_phrases = tag_repository.translated_phrases(chosen_tag)
    unmastered_translated_phrases = []
    for phrase in all_translated_phrases:
        if phrase.mastered == False:
            unmastered_translated_phrases.append(phrase)
    return render_template("sentence_snaps/filtered.html", chosen_tag=chosen_tag, tags_translated_phrases=tags_translated_phrases, all_tags=all_tags, unmastered_translated_phrases=unmastered_translated_phrases, all_languages=all_languages)

@sentence_snaps_blueprint.route("/sentence_snaps/filter_by_language", methods=["POST"])
def filter_by_language():
    if request.form['filter_by_language'] == 'show_all':
        return redirect('/')
    chosen_language_id = request.form['filter_by_language']
    chosen_language = language_repository.select(chosen_language_id)
    all_phrases_in_language = translated_phrase_repository.select_by_language(chosen_language_id)
    all_unmastered_phrases_in_language = []
    for phrase in all_phrases_in_language:
        if phrase.mastered == False:
            all_unmastered_phrases_in_language.append(phrase)
    tags_translated_phrases = tag_translated_phrase_repository.select_all()
    all_tags = tag_repository.select_all()
    all_languages = language_repository.select_all()
    return render_template("sentence_snaps/filtered_by_language.html", all_unmastered_phrases_in_language=all_unmastered_phrases_in_language, chosen_language=chosen_language, tags_translated_phrases=tags_translated_phrases, all_tags=all_tags, all_languages=all_languages)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" type="text/css" href="//use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    <title>Lingua Snaps</title>
</head>
<body>
<main>
    <nav>
        <ul class="navlist">
            <li class="navitem">
                <a href="{{ url_for('base.index') }}">Home</a>
            </li>
            <!-- <li class="navitem">
                <a href="{{ url_for('base.info') }}">How To Use</a>
            </li> -->
            <!-- <li class="navitem">
                <a href="{{ url_for('sentence_snaps_blueprint.sentence_snaps') }}">Sentence Snaps</a>
            </li> -->
            <li class="navitem">
                <a href="{{ url_for('mastered_snaps_blueprint.mastered_snaps') }}">Mastered Snaps</a>
            </li>
            <li class="navitem">
                <a href="{{ url_for('base.play_random') }}">Play A Random Snap</a>
            </li>
            <!-- <li class="navitem">
                <a href="/sentence_snaps/new">Create New Snap</a>
            </li>
            <li class="navitem">
                <a href="{{ url_for('base.create_new_tag') }}">Create A New Tag</a>
            </li> -->
            <!-- <li class="navitem">
                <a href="{{ url_for('language_blueprint.add_new_language') }}">New Language</a>
            </li> -->
        </ul>
    </nav>
    <hr>
    <section>
        {% block content %}
            
        {% endblock content %}
    </section>
</main>
</body>
</html>

templates/create_new_tag.html
{% extends 'base.html' %}

{% block content %}
<div class="solo_blocktext">
    <h1> Create A New Tag</h1>
        <div>
            <form action="/create_new_tag/new" method="POST" class="play_single_entry">
                <p>
                    <label for="new_tag" class="input_text">Name of new tag:</label>
                    <input type="text" name="new_tag" id="new_tag" placeholder="#" required autocomplete="off">
                </p>
                <p class="submitbutton">
                    <input type="submit" value="Submit">
                </p>            
            </form>
            <div>
                Existing tags:
                {% for tag in all_tags %}
                    #{{tag.title}}
                    <form class="delete" action="/create_new_tag/{{tag.id}}/delete" method="POST">
                        <button class="trash-button"><i class="far fa-trash-alt fa-1x"  aria-hidden="true"></i></button>
                    </form>
                {% endfor %}
            </div>
        </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="solo_blocktext">
<h1>Your Sentence Snaps</h1>

<h2>
    <a href="/sentence_snaps/new" class="navitem">Create New Snap</a>
    <a href="/create_new_tag" class="navitem">Create New Tag</a>
    <a href="{{ url_for('language_blueprint.add_new_language') }}" class="navitem">New Language</a>
</h2>
<h3>
  <div>
        <form action="/sentence_snaps/filter" method='POST' class="filter_form">
        <label for="tag_choice">Filter by tag:</label>
            <select name="tag_choice" id="tag_choice" class="filter_drop_down">
                <option value="show_all">Show All</option>
                {% for tag in all_tags %}
                <option value="{{tag.title}}">{{tag.title.capitalize()}}</option>
                {% endfor %}
            </select>
            <span>
                <input type="submit" value="Submit" class="submitbutton">
            </span>
        </form>
      <form action="/sentence_snaps/filter_by_language" method='POST'class="filter_form">
        <label for="filter_by_language">Filter by language:</label>
            <select name="filter_by_language" id="filter_by_language" class="filter_drop_down">
                <option value="show_all">Show All</option>
                {% for language in all_languages %}
                <option value="{{language.id}}">{{language.title.capitalize()}}</option>
                {% endfor %}
            </select>
            <span>
                <input type="submit" value="Submit" class="submitbutton">
            </span>
    </form>
  </div>
</h3>
    <div class="entries">
        {% for unmastered_translated_phrase in unmastered_translated_phrases %}
            <div class="single_entry {{unmastered_translated_phrase.first_language_phrase.difficulty}}">
                <p class="phrase"> '{{unmastered_translated_phrase.first_language_phrase.phrase.capitalize()}}'</p>
                <p class="language"> Practise in: {{unmastered_translated_phrase.language.title.capitalize()}}</p>
                <p class="difficulty">Difficulty: {{unmastered_translated_phrase.first_language_phrase.difficulty.capitalize()}}</p>  
                <div class="buttons">
                    <a href="/sentence_snaps/{{unmastered_translated_phrase.id}}/play">Play</a>
                    <a href="/sentence_snaps/{{unmastered_translated_phrase.id}}/edit">Edit</a>
                    <form class="delete" action="/sentence_snaps/{{unmastered_translated_phrase.id}}/delete" method="POST">
                        <button class="trash-button"><i class="far fa-trash-alt fa-2x"  aria-hidden="true" ></i></button>
                    </form>
                <p class="tags">
                    {% for tag_translated_phrase in tag_translated_phrases  %}
                        {% if tag_translated_phrase.translated_phrase.id == unmastered_translated_phrase.id %}
                            #{{tag_translated_phrase.tag.title}}   
                        {% endif %}
                        
                    {% endfor %}
                </p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock content %}